version: "3.8"

services:
  postgres:
    container_name: ${OLTP_POSTGRES_CONTAINER:-typeorm-oltp-postgres}
    environment:
      POSTGRES_DB: ${OLTP_POSTGRES_DB:-typeorm_db}
    ports:
      - "${OLTP_POSTGRES_PORT:-5433}:5432"
    volumes:
      - typeorm_oltp_postgres_data:/var/lib/postgresql/data
    networks:
      - oltp-network

volumes:
  typeorm_oltp_postgres_data:
    name: ${OLTP_POSTGRES_VOLUME:-typeorm_oltp_postgres_data}

networks:
  oltp-network:
    name: ${OLTP_POSTGRES_NETWORK:-oltp-network}
