version: "3.8"

services:
  postgres:
    container_name: ${OLTP_POSTGRES_CONTAINER:-sqlmodel-postgres}
    environment:
      POSTGRES_DB: ${OLTP_POSTGRES_DB:-sqlmodel_db}
    ports:
      - "${OLTP_POSTGRES_PORT:-5434}:5432"
    volumes:
      - sqlmodel-postgres-data:/var/lib/postgresql/data
    networks:
      - sqlmodel-network

volumes:
  sqlmodel-postgres-data:
    name: ${OLTP_POSTGRES_VOLUME:-sqlmodel_postgres_data}

networks:
  sqlmodel-network:
    name: ${OLTP_POSTGRES_NETWORK:-sqlmodel-network}
    driver: bridge
